# Generated by Django 5.1.3 on 2024-11-24 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAIDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('is_sa_citizen', models.BooleanField()),
                ('search_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('said_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='holidaylookup.saidrecord')),
            ],
        ),
    ]
